FROM debian:buster
RUN apt-get update \
    && apt-get upgrade -y \
    php-cgi php-common php-fpm php-pear php-mbstring \
    php-zip php-net-socket php-gd php-xml-util \
    php-gettext php-mysql php-bcmath vim curl unzip wget git vim -y 

RUN mkdir -p /var/www/html \
    && chmod 777 /var/www/html
WORKDIR /var/www/html
RUN wget http://wordpress.org/latest.tar.gz \
    && tar -xzvf latest.tar.gz && rm -rf latest.tar.gz \
    && cp ./wordpress/wp-config-sample.php ./wordpress/wp-config.php
#   cp /var/www/html/wordpress/wp-config-sample.php /var/www/html/wordpress/wp-config.php ;\
#  touch word.sh;
 COPY ./tools/word.sh /var/www/html/word.sh
 RUN chmod +x $PWD/word.sh
 RUN chown -R www-data:www-data  /var/www/html/wordpress
#RUN sed -i 's/listen = /run/php/php7.3-fpm.sock/listen = 9000/g' /etc/php/7.3/fpm/pool.d/www.conf
RUN mkdir /run/php/
RUN sed -i '/listen =/c listen = 9000' /etc/php/7.3/fpm/pool.d/www.conf

EXPOSE 9000

 ENTRYPOINT sh word.sh && sleep 800